repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
    - id: tflint
      args:
        - "--call-module-type=all"
        - "--config=.tflint.hcl"
        - "--chdir=terraform"
    - id: terraform-validate
    - id: terraform-fmt

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.108.0
  hooks:
    - id: terraform_tfsec
    - id: terraform_docs
    - id: terraform_checkov
      args:
        - --args=--framework
        - --args=terraform

- repo: https://github.com/ansible/ansible-lint
  rev: v26.6.0
  hooks:
    - id: ansible-lint
      args: [ansible]

- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
    - id: yamllint
      files: \.(ya?ml)$
