# SPDX-License-Identifier: MIT-0
---
ha_vip_address: "{{ vip_address }}"
ha_vip_prefix: "{{ vip_prefix }}"

ha_vip_api_port: "{{ vip_api_port }}"
ha_kube_api_port: "{{ kube_api_port }}"

ha_vrrp_interface: "{{ ansible_default_ipv4.interface }}"
ha_vrrp_router_id: 51
ha_keepalived_master_priority: 101
ha_keepalived_backup_priority: 100

ha_haproxy_stats_enabled: "{{ haproxy_stats_enabled }}"
ha_haproxy_balance_algorithm: "{{ haproxy_balance_algorithm }}"
