# SPDX-License-Identifier: MIT-0
---
- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
    enabled: true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
